BEGIN;
DROP VIEW IF EXISTS v_user_profile;
DROP TABLE IF EXISTS spot_visit_photos;
DROP TABLE IF EXISTS spot_visits;
DROP TABLE IF EXISTS spot_photos;
DROP TABLE IF EXISTS spot_species;
DROP TABLE IF EXISTS user_spots;
DROP TABLE IF EXISTS zone_species;
DROP TABLE IF EXISTS zones;
DROP TABLE IF EXISTS mushrooms;
DROP TABLE IF EXISTS note_photos;
DROP TABLE IF EXISTS files;
DROP TABLE IF EXISTS user_notes;
DROP TABLE IF EXISTS user_offline_maps;
DROP TABLE IF EXISTS user_alerts;
DROP TABLE IF EXISTS user_settings;
DROP TABLE IF EXISTS users;
DROP TYPE IF EXISTS download_status;
DROP TYPE IF EXISTS alert_type;
DROP TYPE IF EXISTS subscription_status;
COMMIT;
