export enum Scene {
  Landing = '/',
  Map = '/map',
  Zone = '/zone',
  Spots = '/spots',
  Spot = '/spot',
  Picker = '/picker',
  Mushroom = '/mushroom',
  Settings = '/settings',
  Download = '/download',
  Privacy = '/privacy',
  Terms = '/terms',
  Login = '/login',
  Signup = '/signup',
  Premium = '/premium',
  AuthCallback = '/auth/callback',
}
